networks:
  openwebui-nw:
    driver: bridge


services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - /opt/apps/persistence/openwebui/backend/data:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-53333}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://host.docker.internal:11434'
      - 'WEBUI_SECRET_KEY='
      - 'DATABASE_URL=postgresql://user:password@postgres:5432/openwebui-db'
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - openwebui-nw
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    volumes:
      - /opt/apps/persistence/openwebui/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openwebui-db
    networks:
      - openwebui-nw
    restart: unless-stopped

