networks:
  openwebui-nw:
    driver: bridge

services:
  ollama:
    volumes:
      - /usr/share/ollama/.ollama/:/root/.ollama/
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    networks:
      - openwebui-nw
  
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - /opt/apps/persistence/openwebui/backend/data:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-53333}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - 'DATABASE_URL=postgresql://user:password@postgres:5432/openwebui-db'
    networks:
      - openwebui-nw
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    volumes:
      - /opt/apps/persistence/openwebui/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openwebui-db
    networks:
      - openwebui-nw
    restart: unless-stopped

